label.login.text.title.1=Shala - Kost Management
label.login.text.subtitle.1=Sign in to your account
label.login.text.subtitle.description.1=Enter your email and password to log in

label.login.textField.username=Username
label.login.textField.username.promptText=Enter your username

label.login.passwordField.password=Password
label.login.passwordField.promptText=Enter your password

label.login.text.forgetPassword=Forget password?
label.login.text.dontHaveAccount=Don't have an account? Register

button.login.submit.login.1=Login