label.register.text.title.1=Shala - Kost Management
label.register.text.subtitle.1=Create your account
label.register.text.subtitle.description.1=Create your first credential before use Shala

label.register.textField.username=Username
label.register.textField.username.promptText=Create your username

label.register.passwordField.password=Password
label.register.passwordField.promptText=Min 8 character and a symbol

label.register.choiceBox.role=Choose Role
label.register.choiceBox.securityQuestions=Choose Security Question

label.register.textField.securityAnswer=Your Answer
label.register.textField.securityAnswer.promptText=Enter your security answer

label.register.text.haveAnAccount=Have an account? Login

button.register.submit.register.1=Create Account